'use client'
import { useState, useEffect, useCallback } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { ScrollArea } from '@/components/ui/scroll-area'
import { useToast } from '@/hooks/use-toast'
import { Fuel, Wrench, Wallet, Coffee, AlertOctagon, Plus, Loader2, TrendingUp, Truck, RefreshCw } from 'lucide-react'

const fmt = (n: number) => '$' + n.toLocaleString('es-UY')
const hoy = () => new Date().toISOString().split('T')[0]
const primerDiaMes = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-01` }
const tipoConfig: Record<string, { label: string; icon: any; color: string; bg: string }> = { combustible: { label: 'Combustible', icon: Fuel, color: 'text-orange-700', bg: 'border-orange-300 bg-orange-50' }, sueldo: { label: 'Sueldo', icon: Wallet, color: 'text-blue-700', bg: 'border-blue-300 bg-blue-50' }, mantenimiento: { label: 'Mantenimiento', icon: Wrench, color: 'text-purple-700', bg: 'border-purple-300 bg-purple-50' }, viatico: { label: 'Viático', icon: Coffee, color: 'text-amber-700', bg: 'border-amber-300 bg-amber-50' }, multa: { label: 'Multa', icon: AlertOctagon, color: 'text-red-700', bg: 'border-red-300 bg-red-50' } }

export function CostosRepartidorTab() {
  const { toast } = useToast()
  const [repartidores, setRepartidores] = useState<any[]>([])
  const [costos, setCostos] = useState<any[]>([])
  const [rentabilidad, setRentabilidad] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [showForm, setShowForm] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [filtroRepartidor, setFiltroRepartidor] = useState('todos')
  const [filtroTipo, setFiltroTipo] = useState('todos')
  const [fechaDesde, setFechaDesde] = useState(primerDiaMes())
  const [fechaHasta, setFechaHasta] = useState(hoy())
  const [formRep, setFormRep] = useState(''); const [formTipo, setFormTipo] = useState('combustible'); const [formMonto, setFormMonto] = useState(''); const [formFecha, setFormFecha] = useState(hoy()); const [formDetalle, setFormDetalle] = useState(''); const [formLitros, setFormLitros] = useState(''); const [formKm, setFormKm] = useState(''); const [formForma, setFormForma] = useState('efectivo')

  const fetchRepartidores = useCallback(async () => { try { const res = await fetch('/api/repartidores'); const d = await res.json(); setRepartidores(Array.isArray(d) ? d : (d.repartidores || [])) } catch {} }, [])
  const fetchCostos = useCallback(async () => { setRefreshing(true); try { const params = new URLSearchParams(); if (filtroRepartidor !== 'todos') params.set('repartidor_id', filtroRepartidor); if (filtroTipo !== 'todos') params.set('tipo', filtroTipo); if (fechaDesde) params.set('fecha_desde', fechaDesde); if (fechaHasta) params.set('fecha_hasta', fechaHasta); const res = await fetch(`/api/costos-repartidor?${params}`, { cache: 'no-store' }); if (!res.ok) throw new Error(); const data = await res.json(); setCostos(data.costos || []) } catch { toast({ title: 'Error', variant: 'destructive' }) } finally { setLoading(false); setRefreshing(false) } }, [filtroRepartidor, filtroTipo, fechaDesde, fechaHasta, toast])
  const fetchRentabilidad = useCallback(async () => { try { const params = new URLSearchParams(); params.set('fecha_desde', fechaDesde); params.set('fecha_hasta', fechaHasta); const res = await fetch(`/api/rentabilidad-repartidor?${params}`); if (!res.ok) return; const data = await res.json(); setRentabilidad(data.repartidores || []) } catch {} }, [fechaDesde, fechaHasta])
  useEffect(() => { fetchRepartidores() }, [fetchRepartidores]); useEffect(() => { fetchCostos(); fetchRentabilidad() }, [fetchCostos, fetchRentabilidad])

  const handleSubmit = async () => { if (!formRep) { toast({ title: 'Error', variant: 'destructive' }); return } if (!formMonto || Number(formMonto) <= 0) { toast({ title: 'Error', variant: 'destructive' }); return } const rep = repartidores.find(r => r.id === formRep); if (!window.confirm(`Registrar ${tipoConfig[formTipo]?.label} para ${rep?.nombre}: ${fmt(Number(formMonto))}?`)) return; setSubmitting(true); try { const body: any = { repartidor_id: formRep, tipo: formTipo, monto: Number(formMonto), fecha: formFecha, detalle: formDetalle, forma: formForma }; if (formTipo === 'combustible') { if (formLitros) body.litros = Number(formLitros); if (formKm) body.km_odometro = Number(formKm) } const res = await fetch('/api/costos-repartidor', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (res.ok) { toast({ title: '✅ Costo registrado' }); setFormRep(''); setFormMonto(''); setFormDetalle(''); setFormLitros(''); setFormKm(''); setShowForm(false); fetchCostos(); fetchRentabilidad() } } catch {} finally { setSubmitting(false) } }

  if (loading) return <div className="flex justify-center py-12"><Loader2 className="h-8 w-8 animate-spin text-orange-600" /></div>
  const totalCostos = costos.reduce((s, c) => s + c.monto, 0)
  const totalPorTipo = costos.reduce((acc, c) => { acc[c.tipo] = (acc[c.tipo] || 0) + c.monto; return acc }, {} as Record<string, number>)

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-2"><div className="flex items-center gap-2 flex-wrap"><Select value={filtroRepartidor} onValueChange={setFiltroRepartidor}><SelectTrigger className="w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="todos">Todos</SelectItem>{repartidores.map(r => <SelectItem key={r.id} value={r.id}>{r.nombre}</SelectItem>)}</SelectContent></Select><Select value={filtroTipo} onValueChange={setFiltroTipo}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="todos">Todos</SelectItem>{Object.entries(tipoConfig).map(([k, v]) => <SelectItem key={k} value={k}>{v.label}</SelectItem>)}</SelectContent></Select><Input type="date" value={fechaDesde} onChange={e => setFechaDesde(e.target.value)} className="w-auto" /><span className="text-gray-400">→</span><Input type="date" value={fechaHasta} onChange={e => setFechaHasta(e.target.value)} className="w-auto" /><Button variant="outline" size="sm" onClick={() => { fetchCostos(); fetchRentabilidad() }} disabled={refreshing}><RefreshCw className={`h-4 w-4 ${refreshing ? 'animate-spin' : ''}`} /></Button></div><Button onClick={() => setShowForm(true)} className="bg-orange-600 hover:bg-orange-700"><Plus className="h-4 w-4 mr-1" /> Nuevo Costo</Button></div>
      {showForm && <Card className="border-orange-300"><CardHeader><CardTitle className="text-lg flex items-center gap-2"><Fuel className="h-5 w-5 text-orange-600" /> Registrar Costo</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><div><Label className="text-xs uppercase font-bold">Repartidor *</Label><Select value={formRep} onValueChange={setFormRep}><SelectTrigger><SelectValue placeholder="--" /></SelectTrigger><SelectContent>{repartidores.map(r => <SelectItem key={r.id} value={r.id}><span className="inline-flex items-center gap-2"><span className="w-2 h-2 rounded-full" style={{ backgroundColor: r.color }} />{r.nombre}</span></SelectItem>)}</SelectContent></Select></div><div><Label className="text-xs uppercase font-bold">Tipo *</Label><Select value={formTipo} onValueChange={setFormTipo}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(tipoConfig).map(([k, v]) => <SelectItem key={k} value={k}>{v.label}</SelectItem>)}</SelectContent></Select></div><div><Label className="text-xs uppercase font-bold">Fecha *</Label><Input type="date" value={formFecha} onChange={e => setFormFecha(e.target.value)} /></div><div><Label className="text-xs uppercase font-bold">Monto *</Label><Input type="number" min="0" value={formMonto} onChange={e => setFormMonto(e.target.value)} className="font-bold" /></div><div><Label className="text-xs uppercase font-bold">Forma</Label><Select value={formForma} onValueChange={setFormForma}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="efectivo">Efectivo</SelectItem><SelectItem value="transferencia">Transferencia</SelectItem><SelectItem value="tarjeta">Tarjeta</SelectItem></SelectContent></Select></div><div><Label className="text-xs uppercase font-bold">Detalle</Label><Input value={formDetalle} onChange={e => setFormDetalle(e.target.value)} /></div></div>{formTipo === 'combustible' && <div className="grid grid-cols-2 gap-3 bg-orange-50 p-3 rounded border border-orange-200"><div><Label className="text-xs">Litros</Label><Input type="number" step="0.01" value={formLitros} onChange={e => setFormLitros(e.target.value)} /></div><div><Label className="text-xs">KM Odómetro</Label><Input type="number" value={formKm} onChange={e => setFormKm(e.target.value)} /></div></div>}<div className="flex gap-2 justify-end"><Button variant="outline" onClick={() => setShowForm(false)}>Cancelar</Button><Button onClick={handleSubmit} disabled={submitting || !formRep || !formMonto} className="bg-orange-600 hover:bg-orange-700">{submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Registrar'}</Button></div></CardContent></Card>}
      {rentabilidad.length > 0 && <Card className="border-emerald-300 bg-emerald-50/50"><CardHeader><CardTitle className="text-base flex items-center gap-2"><TrendingUp className="h-5 w-5 text-emerald-600" /> Rentabilidad por Repartidor</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-emerald-100"><tr><th className="p-2 text-left">Repartidor</th><th className="p-2 text-right">Ventas</th><th className="p-2 text-right">Costos</th><th className="p-2 text-right">Ganancia</th><th className="p-2 text-right">Margen</th></tr></thead><tbody>{rentabilidad.map(r => <tr key={r.id} className="border-b"><td className="p-2"><span className="font-bold">{r.nombre}</span></td><td className="p-2 text-right font-bold text-emerald-700">{fmt(r.ingresos.ventas_total)}</td><td className="p-2 text-right font-bold text-red-700">{fmt(r.costos.total)}</td><td className={`p-2 text-right font-black ${r.ganancia_neta >= 0 ? 'text-emerald-700' : 'text-red-700'}`}>{fmt(r.ganancia_neta)}</td><td className={`p-2 text-right ${r.margen_pct >= 0 ? 'text-emerald-700' : 'text-red-700'}`}>{r.margen_pct}%</td></tr>)}</tbody></table></div></CardContent></Card>}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Card className="border-orange-200"><CardContent className="p-4 text-center"><p className="text-xs uppercase font-bold text-gray-500">Total Costos</p><p className="text-2xl font-black text-orange-700">{fmt(totalCostos)}</p><p className="text-xs text-gray-500">{costos.length} movimiento(s)</p></CardContent></Card>{Object.entries(tipoConfig).map(([k, cfg]) => { const t = totalPorTipo[k] || 0; const Icon = cfg.icon; return <Card key={k} className={cfg.bg}><CardContent className="p-4 flex items-center gap-3"><div className={`p-2 rounded-full bg-white ${cfg.color}`}><Icon className="h-5 w-5" /></div><div><p className="text-xs uppercase font-bold text-gray-600">{cfg.label}</p><p className={`text-xl font-black ${cfg.color}`}>{fmt(t)}</p></div></CardContent></Card>})}
      </div>
      <Card><CardHeader><CardTitle className="text-base flex items-center gap-2"><Truck className="h-5 w-5 text-orange-600" /> Movimientos ({costos.length})</CardTitle></CardHeader><CardContent>{costos.length === 0 ? <p className="text-center text-sm text-gray-400 py-8">No hay costos</p> : <ScrollArea className="max-h-[500px]"><div className="flex flex-col gap-2 pr-3">{costos.map(c => { const cfg = tipoConfig[c.tipo] || tipoConfig.viatico; const Icon = cfg.icon; return <div key={c.id} className={`flex items-center gap-3 rounded-lg border p-3 ${cfg.bg}`}><div className={`p-2 rounded-full bg-white ${cfg.color}`}><Icon className="h-4 w-4" /></div><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className="font-bold text-sm">{c.repartidor?.nombre || '?'}</span><Badge variant="outline" className={`text-[10px] ${cfg.color} ${cfg.bg}`}>{cfg.label}</Badge><span className="text-xs text-gray-500">{new Date(c.fecha).toLocaleDateString('es-UY')}</span></div>{c.detalle && <p className="text-xs text-gray-600 truncate">{c.detalle}</p>}{c.litros != null && c.litros > 0 && <p className="text-[11px] text-orange-700">{c.litros} L</p>}</div><div className="text-right shrink-0"><p className={`font-black ${cfg.color}`}>-{fmt(c.monto)}</p><p className="text-[10px] text-gray-500 uppercase">{c.forma}</p></div></div> })}</div></ScrollArea>}</CardContent></Card>
    </div>
  )
}
