'use client'
import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { useToast } from '@/hooks/use-toast'
import { Upload, Download, Loader2, FileSpreadsheet, AlertCircle, CheckCircle, Info } from 'lucide-react'

const TIPOS = [{ value: 'ventas', label: 'Ventas', icon: '💰', color: 'border-emerald-300 bg-emerald-50/50' }, { value: 'remitos', label: 'Remitos', icon: '📦', color: 'border-orange-300 bg-orange-50/50' }, { value: 'caja', label: 'Caja', icon: '💵', color: 'border-sky-300 bg-sky-50/50' }, { value: 'capital', label: 'Capital', icon: '🏦', color: 'border-violet-300 bg-violet-50/50' }]

export function ImportarTab() {
  const { toast } = useToast()
  const [tipo, setTipo] = useState('ventas'); const [csv, setCsv] = useState(''); const [dryRun, setDryRun] = useState(true); const [importing, setImporting] = useState(false); const [result, setResult] = useState<any>(null)
  const descargarPlantilla = async (t: string) => { try { const res = await fetch(`/api/import?tipo=${t}`); if (!res.ok) throw new Error(); const text = await res.text(); const blob = new Blob([text], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `plantilla-${t}.csv`; document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url); toast({ title: '✅ Plantilla descargada' }) } catch { toast({ title: 'Error', variant: 'destructive' }) } }
  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; const text = await file.text(); setCsv(text); toast({ title: '✅ Archivo cargado' }) }
  const handleImport = async () => { if (!csv.trim()) { toast({ title: 'Error', variant: 'destructive' }); return } if (!dryRun && !window.confirm(`¿Importar ${csv.split('\n').length - 1} filas?`)) return; setImporting(true); setResult(null); try { const res = await fetch('/api/import', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tipo, csv, dry_run: dryRun }) }); const data = await res.json(); if (res.ok) { setResult(data); toast({ title: dryRun ? '🔍 Validación OK' : '✅ Importación completa', description: data.message }) } } catch {} finally { setImporting(false) } }
  return (
    <div className="space-y-4">
      <Card className="border-blue-200 bg-blue-50/30"><CardContent className="p-4"><div className="flex items-start gap-3"><Info className="h-5 w-5 text-blue-600 shrink-0 mt-0.5" /><div className="text-sm text-blue-900"><p className="font-bold">Subí datos desde el inicio de la empresa</p><p>Descargá la plantilla CSV, llenala en Excel y subila.</p></div></div></CardContent></Card>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">{TIPOS.map(t => <Card key={t.value} className={`cursor-pointer transition-all hover:shadow-md ${t.color} ${tipo === t.value ? 'ring-2 ring-blue-400' : ''}`} onClick={() => { setTipo(t.value); setResult(null) }}><CardContent className="p-4"><div className="flex items-center gap-2 mb-1"><span className="text-2xl">{t.icon}</span><p className="font-bold text-sm">{t.label}</p></div><Button size="sm" variant="outline" className="mt-2 w-full" onClick={e => { e.stopPropagation(); descargarPlantilla(t.value) }}><Download className="h-3 w-3 mr-1" /> Plantilla</Button></CardContent></Card>)}
      </div>
      <Card><CardHeader><CardTitle className="text-base flex items-center gap-2"><FileSpreadsheet className="h-5 w-5 text-blue-600" /> Importar <Badge variant="secondary" className="capitalize">{tipo}</Badge></CardTitle></CardHeader><CardContent className="space-y-3">
        <div><Label className="text-xs uppercase font-bold">Subir CSV</Label><input type="file" accept=".csv,.txt" onChange={handleFileUpload} className="block w-full text-sm file:mr-3 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100 cursor-pointer" /></div>
        <div><Label className="text-xs uppercase font-bold">O pegar contenido</Label><Textarea value={csv} onChange={e => setCsv(e.target.value)} placeholder={`Pegá CSV de ${tipo}...`} className="font-mono text-xs mt-1 min-h-[200px]" /><p className="text-xs text-gray-500 mt-1">{csv ? `${csv.split('\n').length} líneas` : 'Vacío'}</p></div>
        <div className="flex items-center gap-3 p-3 bg-amber-50 border border-amber-200 rounded"><input type="checkbox" id="dry-run" checked={dryRun} onChange={e => setDryRun(e.target.checked)} className="h-4 w-4" /><label htmlFor="dry-run" className="text-sm font-medium text-amber-900"><strong>Modo validación (dry run)</strong> — valida pero NO inserta</label></div>
        <div className="flex gap-2 justify-end"><Button variant="outline" onClick={() => { setCsv(''); setResult(null) }}>Limpiar</Button><Button onClick={handleImport} disabled={importing || !csv.trim()} className={dryRun ? 'bg-amber-600 hover:bg-amber-700' : 'bg-blue-600 hover:bg-blue-700'}>{importing ? <Loader2 className="h-4 w-4 animate-spin mr-1" /> : dryRun ? <AlertCircle className="h-4 w-4 mr-1" /> : <Upload className="h-4 w-4 mr-1" />}{dryRun ? 'Validar' : 'Importar'}</Button></div>
      </CardContent></Card>
      {result && <Card className={result.dry_run ? 'border-amber-300' : 'border-emerald-300'}><CardHeader><CardTitle className="text-base flex items-center gap-2">{result.dry_run ? <AlertCircle className="h-5 w-5 text-amber-600" /> : <CheckCircle className="h-5 w-5 text-emerald-600" />}Resultado</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><div className="text-center p-3 bg-gray-50 rounded"><p className="text-2xl font-black text-gray-700">{result.rows_total}</p><p className="text-xs uppercase font-bold text-gray-500">Filas</p></div><div className="text-center p-3 bg-emerald-50 rounded"><p className="text-2xl font-black text-emerald-700">{result.rows_valid}</p><p className="text-xs uppercase font-bold text-emerald-600">Válidas</p></div>{!result.dry_run && <div className="text-center p-3 bg-blue-50 rounded"><p className="text-2xl font-black text-blue-700">{result.rows_inserted}</p><p className="text-xs uppercase font-bold text-blue-600">Insertadas</p></div>}<div className="text-center p-3 bg-red-50 rounded"><p className="text-2xl font-black text-red-700">{result.rows_skipped}</p><p className="text-xs uppercase font-bold text-red-600">Saltadas</p></div></div><div className={`p-3 rounded ${result.dry_run ? 'bg-amber-50' : 'bg-emerald-50'}`}><p className="text-sm font-bold">{result.message}</p></div>{result.errores?.length > 0 && <div><p className="text-sm font-bold text-red-700 mb-2">Errores ({result.errores.length}):</p><div className="max-h-[200px] overflow-y-auto border rounded"><table className="w-full text-xs"><thead className="bg-red-100 sticky top-0"><tr><th className="p-2 text-left">Fila</th><th className="p-2 text-left">Error</th></tr></thead><tbody>{result.errores.map((e: any, i: number) => <tr key={i} className="border-b"><td className="p-2 font-bold">{e.row}</td><td className="p-2">{e.error}</td></tr>)}</tbody></table></div></div>}{result.dry_run && result.rows_valid > 0 && <div className="p-3 bg-blue-50 border border-blue-200 rounded"><p className="text-sm font-bold text-blue-900 mb-2">✅ {result.rows_valid} filas listas</p><Button onClick={() => { setDryRun(false); setTimeout(() => handleImport(), 100) }} className="bg-blue-600 hover:bg-blue-700"><Upload className="h-4 w-4 mr-1" />Confirmar importación</Button></div>}</CardContent></Card>}
    </div>
  )
}
